management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    show-sql: true


logging:
  level:
    ROOT: INFO